"""
Export Manager - Handles model export to various formats
"""
import os
import shutil
from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime

class ExportManager:
    def __init__(self):
        self.supported_formats = ['onnx', 'torchscript', 'openvino', 'coreml', 'tflite']
    
    def get_exportable_models(self, project_path: str) -> List[Dict]:
        """List all trained models that can be exported"""
        models = []
        
        # Scan detection, classification, and segmentation runs
        task_dirs = [
            ("detect", "Detection"),
            ("classify", "Classification"),
            ("segment", "Segmentation")
        ]
        
        for task_dir, task_label in task_dirs:
            runs_dir = os.path.join(project_path, "runs", task_dir)
            
            if not os.path.exists(runs_dir):
                continue
            
            for run_name in os.listdir(runs_dir):
                run_path = os.path.join(runs_dir, run_name)
                weights_dir = os.path.join(run_path, "weights")
                
                if os.path.exists(weights_dir):
                    best_pt = os.path.join(weights_dir, "best.pt")
                    last_pt = os.path.join(weights_dir, "last.pt")
                    
                    if os.path.exists(best_pt):
                        models.append({
                            "name": f"[{task_label}] {run_name} (best)",
                            "path": best_pt,
                            "task_type": task_dir,
                            "size_mb": round(os.path.getsize(best_pt) / (1024 * 1024), 2)
                        })
                    if os.path.exists(last_pt):
                        models.append({
                            "name": f"[{task_label}] {run_name} (last)",
                            "path": last_pt,
                            "task_type": task_dir,
                            "size_mb": round(os.path.getsize(last_pt) / (1024 * 1024), 2)
                        })
        
        return models
    
    def export_model(
        self,
        model_path: str,
        output_dir: str,
        format: str = 'onnx',
        imgsz: int = 640,
        half: bool = False,
        dynamic: bool = False
    ) -> Dict[str, Any]:
        """Export a trained model to the specified format"""
        try:
            from ultralytics import YOLO
            
            if format not in self.supported_formats:
                return {"error": f"Unsupported format: {format}. Supported: {self.supported_formats}"}
            
            # Load model
            model = YOLO(model_path)
            
            # Create output directory
            os.makedirs(output_dir, exist_ok=True)
            
            # Export
            export_path = model.export(
                format=format,
                imgsz=imgsz,
                half=half,
                dynamic=dynamic
            )
            
            # Get export file name
            export_file = os.path.basename(export_path) if isinstance(export_path, str) else "exported_model"
            
            # Move to output directory if not already there
            if os.path.dirname(export_path) != output_dir:
                dest_path = os.path.join(output_dir, export_file)
                if os.path.isfile(export_path):
                    shutil.move(export_path, dest_path)
                elif os.path.isdir(export_path):
                    if os.path.exists(dest_path):
                        shutil.rmtree(dest_path)
                    shutil.move(export_path, dest_path)
                export_path = dest_path
            
            # Generate inference script
            script_path = self._generate_inference_script(output_dir, format, export_file)
            
            return {
                "status": "success",
                "format": format,
                "export_path": export_path,
                "script_path": script_path,
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            return {"error": str(e)}
    
    def _generate_inference_script(self, output_dir: str, format: str, model_file: str) -> str:
        """Generate a Python inference script for the exported model"""
        script_content = f'''"""
Auto-generated inference script for {format.upper()} model
Generated by Singularity Vision
"""
import cv2
import numpy as np
'''
        
        if format == 'onnx':
            script_content += '''import onnxruntime as ort

# Load model
session = ort.InferenceSession("{model_file}")
input_name = session.get_inputs()[0].name

def preprocess(image_path, imgsz=640):
    """Preprocess image for inference"""
    img = cv2.imread(image_path)
    img = cv2.resize(img, (imgsz, imgsz))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.transpose(2, 0, 1)  # HWC to CHW
    img = img.astype(np.float32) / 255.0
    img = np.expand_dims(img, 0)
    return img

def run_inference(image_path):
    """Run inference on an image"""
    input_data = preprocess(image_path)
    outputs = session.run(None, {{input_name: input_data}})
    return outputs

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = run_inference(sys.argv[1])
        print(f"Detections: {{len(result[0][0])}} objects")
'''.format(model_file=model_file)
        
        elif format == 'torchscript':
            script_content += '''import torch

# Load model
model = torch.jit.load("{model_file}")
model.eval()

def preprocess(image_path, imgsz=640):
    """Preprocess image for inference"""
    img = cv2.imread(image_path)
    img = cv2.resize(img, (imgsz, imgsz))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.transpose(2, 0, 1)  # HWC to CHW
    img = img.astype(np.float32) / 255.0
    img = torch.from_numpy(img).unsqueeze(0)
    return img

def run_inference(image_path):
    """Run inference on an image"""
    input_data = preprocess(image_path)
    with torch.no_grad():
        outputs = model(input_data)
    return outputs

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = run_inference(sys.argv[1])
        print(f"Output shape: {{result[0].shape}}")
'''.format(model_file=model_file)
        
        else:
            script_content += f'''
# For {format} format, use the appropriate runtime
# See documentation for specific inference instructions
print("Model exported to: {model_file}")
'''
        
        script_path = os.path.join(output_dir, "inference.py")
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        return script_path

# Singleton instance
export_manager = ExportManager()
